---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Docker
    init: docker build .
    command: exit
  - name: Local deps
    init: |
      sudo apt update -y
      sudo apt upgrade -y
      sudo apt install jq yq curl wget
    command: |
      sudo apt update -y
      sudo apt upgrade -y
      exit

vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - bungcip.better-toml
    - tamasfe.even-better-toml
    - foxundermoon.shell-format
    - yzhang.markdown-all-in-one
    - sndst00m.markdown-github-dark-pack
