name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bundle: ["", "blackhole", "console", "s3", "console,s3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        run: docker buildx build -f Dockerfile --platform="linux/amd64,linux/arm64/v8" --build-arg INCLUDED_SINKS="${{ matrix.bundle }}" .