name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bundle:
          [
            "",
            "blackhole",
            "console",
            "s3",
            "console,s3",
            "generic",
            "elasticsearch",
            "vector",
            "vector,s3",
            "vector,elasticsearch",
            "s3,elasticsearch",
            "elasticsearch,console",
            "vector,console",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        run: docker buildx build -f Dockerfile --platform="linux/amd64,linux/arm64/v8" --build-arg INCLUDED_SINKS="${{ matrix.bundle }}" .
